import newproductsbanner from "../../assets/img/banner-laptop.jpg";
import customebuildsbanner from "../../assets/img/custome-builds.jpg";
import laptopbanner from "../../assets/img/laptopbanner.jpg";
import productImg from "../../assets/img/product-img.jpg";
import productImg0 from "../../assets/img/product-img0.jpg";
import productImg01 from "../../assets/img/product-img01.jpg";
import productImg02 from "../../assets/img/product-img02.jpg";
import productImg2 from "../../assets/img/product-img2.jpg";
import productImg3 from "../../assets/img/product-img3.jpg";
import productImg4 from "../../assets/img/product-img4.jpg";

export const newProducts = {
  banner: newproductsbanner,
  label: "New Products",
  sectionsUrl: "new-products/",
  productsArray: [
    {
      prodId: "001",
      inStock: true,
      prodImg: productImg01,
      rating: 4,
      reviews: ["review 1", "good review", "my review"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "002",
      inStock: false,
      prodImg: productImg02,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "003",
      inStock: true,
      prodImg: productImg0,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "004",
      inStock: false,
      prodImg: productImg4,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
    {
      prodId: "005",
      inStock: true,
      prodImg: productImg3,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "006",
      inStock: false,
      prodImg: productImg4,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
  ],
};

export const customeProducts = {
  banner: "",
  label: "Custome Builds",
  sectionsUrl: "custome-builds/",
  productsArray: [
    {
      prodId: "001",
      inStock: true,
      prodImg: productImg,
      rating: 4,
      reviews: ["review 1", "good review", "my review"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "002",
      inStock: false,
      prodImg: productImg2,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "003",
      inStock: true,
      prodImg: productImg3,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "004",
      inStock: false,
      prodImg: productImg4,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
    {
      prodId: "005",
      inStock: true,
      prodImg: productImg0,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "006",
      inStock: false,
      prodImg: productImg02,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
  ],
};

export const laptops = {
  banner: laptopbanner,
  label: "Lenovo Laptops",
  sectionsUrl: "custome-builds/",
  productsArray: [
    {
      prodId: "001",
      inStock: true,
      prodImg: productImg02,
      rating: 4,
      reviews: ["review 1", "good review", "my review"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "002",
      inStock: false,
      prodImg: productImg3,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "003",
      inStock: true,
      prodImg: productImg4,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "004",
      inStock: false,
      prodImg: productImg4,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
    {
      prodId: "005",
      inStock: true,
      prodImg: productImg0,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 467.0,
      price: 399.0,
    },
    {
      prodId: "006",
      inStock: false,
      prodImg: productImg02,
      rating: 4,
      reviews: ["review 1", "good review", "my review", "more reviews"],
      prodDesc: "Ex Display: MSI Pro 16 Flex-036AU 15. MultiTouch all-in-on...",
      oldPrice: 267.0,
      price: 199.0,
    },
  ],
};
